name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install scdoc
      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin
      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin
      - name: Make DMG
        run: make dmg-universal
      - name: Upload Application
        run: |
          mv ./target/release/osx/rust_calculator.dmg ./rust_calculator-${GITHUB_REF##*/}.dmg
          ./.github/workflows/upload_asset.sh ./rust_calculator-${GITHUB_REF##*/}.dmg $GITHUB_TOKEN

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload portable executable
        run: |
          cp ./target/release/rust_calculator.exe ./rust_calculator-${GITHUB_REF##*/}-portable.exe
          ./.github/workflows/upload_asset.sh \
            ./rust_calculator-${GITHUB_REF##*/}-portable.exe $GITHUB_TOKEN

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev \
            libxcb-xfixes0-dev libxkbcommon-dev
      - name: Upload Assets
        run: |
          ./.github/workflows/upload_asset.sh ./rust_calculator.1.gz $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./rust_calculator-msg.1.gz $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./rust_calculator.5.gz $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./rust_calculator-bindings.5.gz $GITHUB_TOKEN
